function [fitresult, gof] = createFit(row, column,m1,m2,stde)
%CREATEFIT1(ROW,COLUMN)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : row
%      Y Output: column
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Feb-2019 11:15:15


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( row, column );

% Set up fittype and options.
ft = fittype( 'a+((b-a)/(1+exp(-c*x)*d))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [m1-200 m2-stde -Inf m2-stde];
opts.StartPoint = [0.655740699156587 0.0357116785741896 0.849129305868777 0.933993247757551];
opts.Upper = [m1+200 m2+stde Inf m2+stde];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'column vs. row', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel row
% ylabel column
% grid on


