function [fitresult, gof] = sigmoid_fit(z, Idepth)
%CREATEFIT1(XPOINTS,YPOINTS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xPoints
%      Y Output: yPoints
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Dec-2019 12:51:06

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( z, Idepth );

% Set up fittype and options.
ft = fittype( '1/(1+exp(-a*(x-b)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 z(1)];
opts.Upper = [Inf z(end)];
opts.StartPoint = [1 z(end/2)];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
